Complementaria métodos computacionales

Catalina Fuentes y Silvana Archila


Taller #3

Ejercicio 1: Multiplicación de matrices

In [27]:
import numpy as np 
import sympy as sym

In [28]:
#Creando algoritmo que multiplica matrices
def multiplicar_matrices(matrizA, matrizB):

    #Alerta si las matrices no se pueden multiplicar 
    if matrizA.shape[1] != matrizB.shape[0]:
        x = str("Las dimensiones de las matrices no permiten la multiplicación.")
        compatibles = 0
        return x

    compatibles = 1
    
    #Creando matriz de ceros con las dimensiones adecuadas
    filas_multip = matrizA.shape[0]
    colum_multip = matrizB.shape[1]
    multiplicacion = np.zeros((filas_multip, colum_multip))

    #Realizando la multiplicación de las matrices
    if compatibles != 0:
        for i in range(filas_multip):
            for j in range(colum_multip):
                for k in range(matrizB.shape[0]):
                    multiplicacion[i][j] += matrizA[i][k] * matrizB[k][j]

        return multiplicacion

Hallando resultados de las operaciones dadas

In [29]:
#A
matrizA = np.array([[5,-4,-2], [5,-5,4], [2,5,-4], [-5,4,3], [3,-4,-3]])
matrizB = np.array([[5], [-2], [-3]])

multiplicacion = multiplicar_matrices(matrizA,matrizB)

print("La multiplicación de las 2 matrices dadas tiene como resultado:" )
print(multiplicacion)

La multiplicación de las 2 matrices dadas tiene como resultado:
[[ 39.]
 [ 23.]
 [ 12.]
 [-42.]
 [ 32.]]


In [30]:
#B
matrizA = np.array([[0,-1,-1,3], [5,-5,-2,2], [1,0,4,5]])
matrizB = np.array([[0,-3], [-2,-1], [3,-3]])

multiplicacion = multiplicar_matrices(matrizA,matrizB)

print(multiplicacion)

Las dimensiones de las matrices no permiten la multiplicación.


In [31]:
#C
matrizA = np.array([[2,-5,5,1], [5,2,-7,-6], [-6,-1,7,-4], [5,4,1,-5]])
matrizB = np.array([[0,4,-7,1,-6], [-1,-6,-5,1,1], [2,-1,-6,5,-5], [-3,-6,6,3,5]])

multiplicacion = multiplicar_matrices(matrizA,matrizB)

print("La multiplicación de las 2 matrices dadas tiene como resultado:" )
print(multiplicacion)


La multiplicación de las 2 matrices dadas tiene como resultado:
[[ 12.  27. -13.  25. -37.]
 [  2.  51. -39. -46. -23.]
 [ 27.  -1. -19.  16. -20.]
 [ 13.  25. -91.  -1. -56.]]


Utilizando dos matrices cuadradas, demostrar que la multiplicación no es conmutativa.

In [32]:
#Matrices cuadradas que utilizaremos
matrizA = np.array([[1,2,3], [9,8,7], [4,5,6]])
matrizB = np.array([[-1,3,2], [-4,-2,5], [0,5,3]])


In [33]:
#Realizando AxB
multiplicacion = multiplicar_matrices(matrizA,matrizB)

print("La multiplicación de AxB tiene como resultado:" )
print(multiplicacion)

La multiplicación de AxB tiene como resultado:
[[ -9.  14.  21.]
 [-41.  46.  79.]
 [-24.  32.  51.]]


In [34]:
#Realizando BxA
multiplicacion = multiplicar_matrices(matrizB,matrizA)

print("La multiplicación de BxA tiene como resultado:" )
print(multiplicacion)

La multiplicación de BxA tiene como resultado:
[[34. 32. 30.]
 [-2.  1.  4.]
 [57. 55. 53.]]


Así, observamos que AxB tiene un resultado distinto a BxA, lo cual demuestra que la multiplicación de matrices no es conmutativa